/**
 * Prints a fresh set of secrets for a .env file.
 *
 * Uses only Node's built-in crypto, so it works identically on Windows,
 * macOS and Linux — no openssl, no WSL.
 *
 * Usage:
 *   npm run gen:secrets              # prints every value
 *   npm run gen:secrets -- --demo    # only the subset .env.demo needs
 *   npm run gen:secrets -- --write   # writes .env.demo (refuses to overwrite)
 */
import { generateKeyPairSync, randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const args = new Set(process.argv.slice(2));
const demoOnly = args.has('--demo') || args.has('--write');
const write = args.has('--write');

// Ed25519 keypair for EdDSA-signed access tokens. Base64 so each PEM survives
// as a single .env line.
const { privateKey, publicKey } = generateKeyPairSync('ed25519');
const privatePem = privateKey.export({ type: 'pkcs8', format: 'pem' }).toString();
const publicPem = publicKey.export({ type: 'spki', format: 'pem' }).toString();
const b64 = (s) => Buffer.from(s, 'utf8').toString('base64');

const hex = (bytes) => randomBytes(bytes).toString('hex');
/** A readable but strong password for the seeded demo accounts. */
const password = () => randomBytes(12).toString('base64url');

const shared = {
  JWT_PRIVATE_KEY_B64: b64(privatePem),
  JWT_PUBLIC_KEY_B64: b64(publicPem),
  INFERENCE_HMAC_SECRET: hex(32),
  SEED_ADMIN_PASSWORD: password(),
  SEED_CLINICIAN_PASSWORD: password(),
};

const fullStackOnly = {
  FIELD_ENCRYPTION_KEY_HEX: hex(32),
  CSRF_SECRET: hex(32),
  S3_ACCESS_KEY: `pv-${randomBytes(8).toString('hex')}`,
  S3_SECRET_KEY: hex(24),
  MONGO_ROOT_USER: 'pneumovision',
  MONGO_ROOT_PASSWORD: password(),
  REDIS_PASSWORD: password(),
};

const values = demoOnly ? shared : { ...shared, ...fullStackOnly };

if (write) {
  const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
  const target = resolve(root, '.env.demo');
  if (existsSync(target)) {
    console.error(`${target} already exists — delete it first if you want fresh secrets.`);
    process.exit(1);
  }
  const template = [
    '# Generated by `npm run gen:secrets -- --write`. Do not commit.',
    '# Demo profile: no Redis, S3, encryption or CSRF secrets needed.',
    '',
    'DEMO_MODE=true',
    'NODE_ENV=development',
    'LOG_LEVEL=info',
    'API_PORT=4000',
    'WEB_ORIGIN=http://localhost:5173',
    '',
    '# Empty MONGO_URI starts an in-process mongodb-memory-server.',
    'MONGO_URI=',
    'MONGO_DB=pneumovision',
    '',
    'INFERENCE_URL=http://127.0.0.1:8000',
    'MOCK_MODE=true',
    'DEFAULT_THETA=0.75',
    '',
    'SEED_ADMIN_EMAIL=admin@pneumovision.local',
    'SEED_CLINICIAN_EMAIL=clinician@pneumovision.local',
    '',
    ...Object.entries(values).map(([k, v]) => `${k}=${v}`),
    '',
  ].join('\n');
  writeFileSync(target, template, 'utf8');
  console.log(`wrote ${target}`);
  console.log(`\n  admin:     admin@pneumovision.local / ${values.SEED_ADMIN_PASSWORD}`);
  console.log(`  clinician: clinician@pneumovision.local / ${values.SEED_CLINICIAN_PASSWORD}\n`);
} else {
  console.log(
    demoOnly
      ? '# Demo secrets — paste into .env.demo\n'
      : '# Secrets — paste into .env (never commit this output)\n',
  );
  for (const [k, v] of Object.entries(values)) console.log(`${k}=${v}`);
}
